### ISSUE TITLE
Prevent exception when "instant" GET param is given to parameters endpoint

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-web-api#47]
```
curl "http://localhost:2000/api/1/parameters?instant=2014-01-01"
```

raises

```
15:17:16,706 ERROR [openfisca_web_api.application] 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/cbenz/Dev/openfisca/openfisca-web-api/openfisca_web_api/application.py", line 27, in _launch_debugger_on_exception
    return app(environ, start_response)
  File "/home/cbenz/Dev/openfisca/openfisca-web-api/openfisca_web_api/application.py", line 66, in set_x_api_version_header
    res = req.get_response(app)
  File "/usr/lib/python2.7/dist-packages/webob/request.py", line 1317, in send
    application, catch_exc_info=False)
  File "/usr/lib/python2.7/dist-packages/webob/request.py", line 1281, in call_application
    app_iter = application(self.environ, start_response)
  File "/home/cbenz/Dev/openfisca/openfisca-web-api/openfisca_web_api/application.py", line 42, in set_environment
    return app(req.environ, start_response)
  File "/home/cbenz/Dev/openfisca/openfisca-web-api/openfisca_web_api/urls.py", line 115, in router
    return app(req.environ, start_response)
  File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 130, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 195, in call_func
    return self.func(req, *args, **kwargs)
  File "/home/cbenz/Dev/openfisca/openfisca-web-api/openfisca_web_api/controllers/parameters.py", line 88, in api1_parameters
    for name in data['names']:
TypeError: 'NoneType' object is not iterable
> /home/cbenz/Dev/openfisca/openfisca-web-api/openfisca_web_api/controllers/parameters.py(88)api1_parameters()
     87             )
---> 88         for name in data['names']:
     89             name_fragments = name.split('.')

```

**Comment by MattiSG** [comment]
This actually happens only if the `instant` parameter is given without any `name` parameter.

This was never documented, and no user ever complained about it. I fixed the documentation in https://github.com/openfisca/openfisca-gitbook/pull/34.
