### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 9: ordinal not in range(128)

### ISSUE THREAD

**Issue by clemdherbe** [openfisca/openfisca-web-api#5]
On Windows, opening URL http://localhost:2014/ in Chrome, I get this stack trace :

----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 49588)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\paste-1.7.5.1-py2.7.egg\paste\httpserver.py", line 1068, in process_request_in_thread
    self.finish_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python27\lib\SocketServer.py", line 651, in __init__
    self.handle()
  File "C:\Python27\lib\site-packages\paste-1.7.5.1-py2.7.egg\paste\httpserver.py", line 442, in handle
    BaseHTTPRequestHandler.handle(self)
  File "C:\Python27\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "C:\Python27\lib\site-packages\paste-1.7.5.1-py2.7.egg\paste\httpserver.py", line 437, in handle_one_request
    self.wsgi_execute()
  File "C:\Python27\lib\site-packages\paste-1.7.5.1-py2.7.egg\paste\httpserver.py", line 287, in wsgi_execute
    self.wsgi_start_response)
  File "c:\Users\clÚment\Desktop\openfisca\openfisca-web-api\openfisca_web_api\application.py", line 41, in set_environment
    return app(req.environ, start_response)
  File "c:\Users\clÚment\Desktop\openfisca\openfisca-web-api\openfisca_web_api\urls.py", line 155, in router
    message = ctx._(u"Path not found: {0}").format(req.path_info),
  File "c:\Users\clÚment\Desktop\openfisca\openfisca-web-api\openfisca_web_api\contexts.py", line 61, in __getattribute__
    return object.__getattribute__(self, name)
  File "c:\Users\clÚment\Desktop\openfisca\openfisca-web-api\openfisca_web_api\contexts.py", line 73, in _
    return self.translator.ugettext
  File "c:\Users\clÚment\Desktop\openfisca\openfisca-web-api\openfisca_web_api\contexts.py", line 61, in __getattribute__
    return object.__getattribute__(self, name)
  File "c:\Users\clÚment\Desktop\openfisca\openfisca-web-api\openfisca_web_api\contexts.py", line 180, in translator
    conf['country_package'], 'i18n'),
  File "C:\Python27\lib\ntpath.py", line 84, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 9: ordinal not in range(128)
----------------------------------------

**Comment by eraviart** [comment]
Change de nom, clÚment
