### ISSUE TITLE
Standard install fails

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-web-api#7]
If I follow the [installation instructions](http://www.openfisca.fr/installation#mac), I get the following error:

    Traceback (most recent call last):
      File "/usr/local/bin/paster", line 9, in <module>
        load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
      File "/Library/Python/2.7/site-packages/paste/script/command.py", line 93, in run
        commands = get_commands()
      File "/Library/Python/2.7/site-packages/paste/script/command.py", line 135, in get_commands
        plugins = pluginlib.resolve_plugins(plugins)
      File "/Library/Python/2.7/site-packages/paste/script/pluginlib.py", line 82, in resolve_plugins
        pkg_resources.require(plugin)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 673, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 576, in resolve
        raise DistributionNotFound(req)
    pkg_resources.DistributionNotFound: OpenFisca-France-Reform-Landais-Piketty-Saez: Not Found for: OpenFisca_Web_API (did you run python setup.py develop?)

**Comment by cbenz** [comment]
Fixed biryani dependencies and removed unmatchable deps.

Documentation still needs to be updated but this is a more general issue.

Please confirm everything is OK.

**Comment by MattiSG** [comment]
Confirmed to work after, for all OpenFisca-* repos and Biryani:

	pip uninstall
	cd <repo>
	git checkout master
	git pull
	python setup.py compile_catalog
	sudo python setup.py develop --no-deps

I can `paster serve --reload development-france.ini`.

This issue may be closed once openfisca/openfisca-web-site#40 is merged.

**Comment by cbenz** [comment]
Thanks
